--------------------------------------------------------
--  Fichier créé - mercredi-mai-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_COM_PK
--------------------------------------------------------

   CREATE SEQUENCE  "INVITE"."SEQ_COM_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "INVITE"."ARTICLE" 
   (	"REF_ART" VARCHAR2(50 BYTE), 
	"LIB_COURT_ART" VARCHAR2(20 BYTE), 
	"LIB_LONG_ART" VARCHAR2(100 BYTE), 
	"PU_ART" FLOAT(126), 
	"QTE_STOCK" NUMBER(*,0), 
	"STOCK_SEUIL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "INVITE"."COMMANDE" 
   (	"NUM_COM" NUMBER(*,0), 
	"LIB_COM" VARCHAR2(50 BYTE), 
	"DATE_COM" DATE, 
	"MT_COM" FLOAT(126), 
	"TVA_COM" FLOAT(126), 
	"MT_TVA" FLOAT(126), 
	"MT_TTC_COM" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETAIL_COM
--------------------------------------------------------

  CREATE TABLE "INVITE"."DETAIL_COM" 
   (	"NUM_COM" NUMBER(*,0), 
	"REF_ART" VARCHAR2(50 BYTE), 
	"QTE_ART" FLOAT(126), 
	"PU_ART" FLOAT(126), 
	"PT_ART" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INVITE.ARTICLE
SET DEFINE OFF;
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_1','Lardons fu CAR','Lardons fumés CARREFOUR','1,61','21','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_2','Papier toi Con do','Papier toilette Confort doux ','2,04','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_3','Lardons na CAR','Lardons nature CARREFOUR ','1,59','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_4','Baguette Rus CAR','Baguette Rustique CARREFOUR','1','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_5','6 Cui poul CAR','Cuisse de poulet CARREFOUR','7,56','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_6','Œufs fr cal mo CAR','Œufs frais calibre moyen CARREFOUR','2,96','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_7','Beurre do CAR','Beurre doux CARREFOUR','3,56','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_8','Escal din ext-fin','Escalopes de dinde extra-fines ','3,14','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_9','Œufs pl air CAR','Œufs plein air CARREFOUR ','3,67','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_10','Pâte feuil CAR','Pâte feuilletée CARREFOUR  ','1,16','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_11','Essuie-t Ult Abs','Essuie-tout Ultra Absorbant ','2,88','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_12','Eau sou Auv','Eau de source d''Auvergne ','1,5','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_13','Spaghetti pzn','Spaghetti Panzanni','0,86','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_14','Riz Bas','Riz Basmati ','1,62','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_15','Lait dem-éc','Lait demi-écrémé ','4,68','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_16','Parm rap AOP','Parmesan râpé AOP ','1,6','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_17','Cam bio AOP','Camembert bio AOP ','1,25','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_18','Poire Wil Bio','Poire Williams Bio ','2,95','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_19','Filets pou jau','Filets de poulet jaune ','10,89','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_20','Farine blé fl T45','Farine de blé fluide T45 ','0,54','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_21','Allumettes fu','Allumettes fumées ','1,53','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_23','Viande ha p b 15%','Viande hachée pur bœuf 15% ','6,15','20','5');
Insert into INVITE.ARTICLE (REF_ART,LIB_COURT_ART,LIB_LONG_ART,PU_ART,QTE_STOCK,STOCK_SEUIL) values ('REF_ART_25','Jamb sup ss cou','Jambon supérieur sans couenne ','2,18','20','5');
REM INSERTING into INVITE.COMMANDE
SET DEFINE OFF;
REM INSERTING into INVITE.DETAIL_COM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger T_UPDATE_MT_TVA_TTC_COM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INVITE"."T_UPDATE_MT_TVA_TTC_COM" 
AFTER INSERT ON DETAIL_COM FOR EACH ROW
DECLARE

BEGIN

  P_UPDATE_MT_TVA_TTC_COM(:NEW.NUM_COM);

END;
/
ALTER TRIGGER "INVITE"."T_UPDATE_MT_TVA_TTC_COM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_UPDATE_MT_TVA_TTC_COM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INVITE"."T_UPDATE_MT_TVA_TTC_COM" 
AFTER INSERT ON DETAIL_COM FOR EACH ROW
DECLARE

BEGIN

  P_UPDATE_MT_TVA_TTC_COM(:NEW.NUM_COM);

END;
/
ALTER TRIGGER "INVITE"."T_UPDATE_MT_TVA_TTC_COM" ENABLE;
--------------------------------------------------------
--  DDL for Procedure P_ADD_ART_COM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INVITE"."P_ADD_ART_COM" 
(
  V_REF_ART IN VARCHAR2 
  , V_NUM_COM IN NUMBER
, V_QTE_ART IN NUMBER 

) AS 

V_PT_ART FLOAT;
V_PU_ART FLOAT;

V_NBRE NUMBER := 0;
V_QTE_ART_INI NUMBER;
v_QTE_T NUMBER;


BEGIN
	
SELECT COUNT(REF_ART), QTE_ART INTO V_NBRE, V_QTE_ART_INI FROM DETAIL_COM WHERE REF_ART = V_REF_ART AND NUM_COM = V_NUM_COM;

SELECT PU_ART INTO V_PU_ART FROM ARTICLE WHERE REF_ART = V_REF_ART;

V_PT_ART := F_PT_ART(V_REF_ART,V_QTE_ART);


IF(V_NBRE>0) THEN 

v_QTE_T := (V_QTE_ART + V_QTE_ART_INI);
V_PT_ART := (v_QTE_T * V_PU_ART);

UPDATE INVITE.DETAIL_COM SET QTE_ART= v_QTE_T, PT_ART= V_PT_ART  WHERE REF_ART=V_REF_ART AND NUM_COM = V_NUM_COM;

ELSE

INSERT INTO INVITE.DETAIL_COM (NUM_COM, REF_ART, QTE_ART, PU_ART, PT_ART)
VALUES(V_NUM_COM,V_REF_ART, V_QTE_ART, V_PU_ART, V_PT_ART);
      
END IF;




      
 P_UPDATE_STOCK(V_REF_ART,(0 - V_QTE_ART));
       
END P_ADD_ART_COM;

/
--------------------------------------------------------
--  DDL for Procedure P_DELETE_COM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INVITE"."P_DELETE_COM" 
(
  V_NUM_COM IN NUMBER 
) AS 
CURSOR CUR IS SELECT REF_ART, QTE_ART FROM DETAIL_COM WHERE NUM_COM = V_NUM_COM;
BEGIN

  FOR TABLE_ROW IN CUR
  LOOP
  P_UPDATE_STOCK(TABLE_ROW.REF_ART,TABLE_ROW.QTE_ART);
  END LOOP;
 
  DELETE FROM DETAIL_COM WHERE NUM_COM = V_NUM_COM;
 
END P_DELETE_COM;

/
--------------------------------------------------------
--  DDL for Procedure P_UPDATE_MT_TVA_TTC_COM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INVITE"."P_UPDATE_MT_TVA_TTC_COM" 
(
  V_NUM_COM IN NUMBER 
) AS 
V_MT_COM FLOAT;
V_MT_TVA FLOAT;
V_MT_TTC_COM FLOAT;
V_TVA_COM FLOAT;
BEGIN

SELECT TVA_COM INTO V_TVA_COM FROM COMMANDE WHERE NUM_COM = V_NUM_COM;

SELECT SUM(PT_ART) INTO V_MT_COM FROM DETAIL_COM WHERE NUM_COM = V_NUM_COM;

V_MT_TVA := (V_MT_COM * V_TVA_COM)/100;

V_MT_TTC_COM := V_MT_COM + V_MT_TVA;

UPDATE COMMANDE SET MT_COM = V_MT_COM, MT_TVA = V_MT_TVA, MT_TTC_COM = V_MT_TTC_COM;

END P_UPDATE_MT_TVA_TTC_COM;

/
--------------------------------------------------------
--  DDL for Procedure P_UPDATE_STOCK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INVITE"."P_UPDATE_STOCK" 
(
  V_REF_ART IN VARCHAR2 
, V_QTE_ART IN NUMBER 
) AS 

V_QTE_ART_INI NUMBER;
V_QTE_ART_F NUMBER;

BEGIN
	
SELECT QTE_STOCK INTO V_QTE_ART_INI FROM ARTICLE WHERE REF_ART = V_REF_ART;

V_QTE_ART_F := (V_QTE_ART_INI + V_QTE_ART);

UPDATE ARTICLE SET QTE_STOCK = V_QTE_ART_F WHERE REF_ART = V_REF_ART;

END P_UPDATE_STOCK;

/
--------------------------------------------------------
--  DDL for Procedure P_VALIDATE_COM
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INVITE"."P_VALIDATE_COM" 
(
  V_NUM_COM IN NUMBER,
  V_LIB_COM IN VARCHAR2,
  V_TVA_COM IN FLOAT
) AS 
BEGIN
  
  INSERT INTO INVITE.COMMANDE (NUM_COM, LIB_COM, DATE_COM, MT_COM, TVA_COM, MT_TVA, MT_TTC_COM)
    VALUES(V_NUM_COM, '', '', 0, V_TVA_COM, 0, 0);
    
END P_VALIDATE_COM;

/
--------------------------------------------------------
--  DDL for Function F_PT_ART
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "INVITE"."F_PT_ART" 
(
  V_REF_ART IN VARCHAR2 
, V_QTE_ART IN NUMBER 
) RETURN FLOAT AS 
V_PU_ART FLOAT;
BEGIN
SELECT PU_ART INTO V_PU_ART FROM ARTICLE WHERE REF_ART = V_REF_ART;

  RETURN V_PU_ART * V_QTE_ART;
END F_PT_ART;

/
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "INVITE"."ARTICLE" ADD CONSTRAINT "ARTICLE_PK" PRIMARY KEY ("REF_ART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("STOCK_SEUIL" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("QTE_STOCK" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("PU_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("LIB_LONG_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("LIB_COURT_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."ARTICLE" MODIFY ("REF_ART" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "INVITE"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("NUM_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INVITE"."COMMANDE" MODIFY ("TVA_COM" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."COMMANDE" MODIFY ("DATE_COM" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."COMMANDE" MODIFY ("LIB_COM" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."COMMANDE" MODIFY ("NUM_COM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETAIL_COM
--------------------------------------------------------

  ALTER TABLE "INVITE"."DETAIL_COM" MODIFY ("PT_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."DETAIL_COM" MODIFY ("PU_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."DETAIL_COM" MODIFY ("QTE_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."DETAIL_COM" MODIFY ("REF_ART" NOT NULL ENABLE);
  ALTER TABLE "INVITE"."DETAIL_COM" MODIFY ("NUM_COM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DETAIL_COM
--------------------------------------------------------

  ALTER TABLE "INVITE"."DETAIL_COM" ADD CONSTRAINT "DETAIL_COM_FK1" FOREIGN KEY ("REF_ART")
	  REFERENCES "INVITE"."ARTICLE" ("REF_ART") ENABLE;
  ALTER TABLE "INVITE"."DETAIL_COM" ADD CONSTRAINT "DETAIL_COM_FK2" FOREIGN KEY ("NUM_COM")
	  REFERENCES "INVITE"."COMMANDE" ("NUM_COM") ENABLE;
